unbreakable-blocks: []
force-field-blocks:
- title: Gold Condom
  block: gold_block
  radius: 4
  meta-name: '&Gold Condom'
  meta-autoset: true
  meta-lore:
  - '&eThis will protect a 8x8x8 area'
  prevent-fire: true
  prevent-place: true
  prevent-destroy: true
  prevent-vehicle-destroy: true
  prevent-enderman-destroy: true
  prevent-explosions: true
  prevent-unprotectable: true
  prevent-item-frame-take: true
  protect-armor-stands: true
  prevent-flow: true
  protect-crops: true
  protect-inventories: true
  prevent-place-blacklist: [153]
  ?welcome-message: true
  ?farewell-message: true
  ?prevent-portal-enter: true
  ?prevent-portal-destination: true
  ?prevent-portal-create: true
  ?prevent-vehicle-enter: true
  ?prevent-vehicle-exit: true
  ?prevent-teleport: true
  command-blacklisting: true
  can-change-owner: true
  enable-on-src: true
  mixing-group: 1
  rentable: true
  rents-limit: 5
  buyable: true
  cuboid: true
  mask-on-disabled: 80
- title: Emerald Condom
  block: emerald_block
  radius: 7
  meta-name: '&bEmerald Condom'
  meta-autoset: true
  meta-lore:
  - '&eThis will protect a 10x10x10 area, other players cannot enter.'
  prevent-entry: true
  prevent-fire: true
  prevent-place: true
  prevent-destroy: true
  prevent-vehicle-destroy: true
  prevent-enderman-destroy: true
  prevent-explosions: true
  prevent-unprotectable: true
  prevent-item-frame-take: true
  protect-armor-stands: true
  prevent-flow: true
  protect-crops: true
  protect-inventories: true
  prevent-place-blacklist: [153]
  ?welcome-message: true
  ?farewell-message: true
  ?prevent-portal-enter: true
  ?prevent-portal-destination: true
  ?prevent-portal-create: true
  ?prevent-vehicle-enter: true
  ?prevent-vehicle-exit: true
  ?prevent-teleport: true
  command-blacklisting: true
  can-change-owner: true
  enable-on-src: true
  mixing-group: 1
  rentable: true
  rents-limit: 5
  buyable: true
  cuboid: true
  mask-on-disabled: 80
- title: Diamond Condom
  block: diamond_block
  radius: 7
  meta-name: '&bDiamond Condom'
  meta-autoset: true
  meta-lore:
  - '&eThis will protect a 14x14x14 area'
  prevent-fire: true
  prevent-place: true
  prevent-destroy: true
  prevent-vehicle-destroy: true
  prevent-enderman-destroy: true
  prevent-explosions: true
  prevent-unprotectable: true
  prevent-item-frame-take: true
  protect-armor-stands: true
  prevent-flow: true
  protect-crops: true
  protect-inventories: true
  prevent-place-blacklist: [153]
  ?welcome-message: true
  ?farewell-message: true
  ?prevent-portal-enter: true
  ?prevent-portal-destination: true
  ?prevent-portal-create: true
  ?prevent-vehicle-enter: true
  ?prevent-vehicle-exit: true
  ?prevent-teleport: true
  command-blacklisting: true
  can-change-owner: true
  enable-on-src: true
  mixing-group: 1
  rentable: true
  rents-limit: 5
  buyable: true
  cuboid: true
  mask-on-disabled: 80
- title: Proximity Snitch
  block: noteblock
  radius: 5
  meta-name: '&1Proximity Snitch'
  meta-autoset: true
  meta-lore:
  - '&9Will report to you when someone'
  - '&9enters your base.'
  - '&9It covers an area of 5 radius'
  snitch: true
  entry-alert: true
  no-conflict: true
  mixing-group: 2
  cuboid: true
  mask-on-disabled: 80
bypass-blocks: []
unprotectable-blocks: []
hiding-mask-blocks: [1,2,3,4,5,7,12,13,17,18,20,24,35,43,45,47,48,49,53,60,67,80,81,82,87,88,89,99,100,108,109,110,123,124,125,128,134,135,136]
repairable-items: [256,257,258,259,261,267,268,269,270,271,272,273,274,275,276,277,278,279,283,284,285,286,290,291,292,293,294,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,346,359]
tool-items: [256,257,258,269,270,271,273,274,275,277,278,279,284,285,286,290,291,292,293,294]
settings:
  auto-allow-clan-on-fields: true
  auto-allow-team-on-fields: false
  blacklisted-worlds: [creative_world]
  check-once-per-block-on-move: false
  default-item-currency: '266'
  disable-alerts-for-admins: true
  disable-bypass-alerts-for-admins: false
  disable-field-break-while-creative: false
  disable-field-place-while-creative: false
  disable-ground-info: false
  disable-simpleclans-hook: false
  drop-on-delete: true
  fence-max-depth: 50
  global-field-limit: 1000000
  lines-per-page: 100
  max-size-translocation-for-redstone: 1000
  max-size-translocation: 100000
  max-target-distance: 100
  no-refund-for-fields: false
  off-by-default: false
  prevent-breaking-hidden: false
  prevent-destroy-everywhere: [creative_world]
  prevent-place-everywhere: [creative_world]
  prevent-removal-if-player-in-field: true
  public-block-details: false
  show-debug-info: false
  show-default-welcome-farewell-messages: true
  sneak-to-place-field: false
  sneak-to-place-normal-block: true
  use-blockids-in-snitches: false
  use-commands-to-rent: true
  version: 14
log:
  bypass-pvp: true
  pvp: true
  bypass-destroy: true
  use: true
  fire: true
  destroy: true
  destroy-area: false
  place-area: false
  entry: true
  unprotectable: true
  bypass-place: true
  place: true
  translocation: true
  rollback: true
  bypass-delete: true
  conflict-place: true
  rents-and-purchases: true
notify:
  destroy: true
  bypass-pvp: true
  bypass-destroy: true
  bypass-unprotectable: true
  bypass-place: true
  place: true
  rollback: true
  translocation: true
  fly-zones: true
warn:
  slow-damage: true
  pvp: true
  instant-heal: true
  launch: true
  fast-damage: true
  use: true
  air: true
  slow-feeding: true
  fire: true
  cannon: true
  destroy-area: true
  destroy: true
  slow-heal: true
  entry: true
  unprotectable: true
  mine: true
  slow-repair: true
  place: true
cuboid:
  visualization-blocktype: glass
  defining-blocktype: obsidian
visualization:
  new-dotted-style: true
  block-type: glass
  seconds: 30
  mark-block-type: obsidian
  end-on-player-move: false
  frame-block-type: glass
  blocks-to-send: 100
  ticks-between-sends: 10
  default-density: 8
  max-fields-to-visualize-at-once: 5
  visualize-on-expand: true
grief-revert:
  min-interval-secs: 30
  black-list:
  - 92
saving:
  frequency-seconds: 1
  max-records-per-snitch: 50
cleanup:
  player-inactivity-purge-days: 180
  purge-banned-players: true
mysql:
  username: ''
  host: localhost
  enable: false
  password: ''
  database: minecraft
  port: 3306
